name: cantara
version: '2.7.1'
summary: Open Source Song Presentation Software for Churches and Small Groups
description: |
  A simple, lightweight but powerful program for song presentation in churches,
  small groups or at karaoke parties.

confinement: strict
base: core24
grade: stable

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]

icon: app.cantara.Cantara.png

apps:
  cantara:
    command: cantara       # binary lives at $SNAP/bin/cantara
    desktop: cantara.desktop
    extensions: [ "kde-neon-6" ]
    plugs:
      - desktop
      - desktop-legacy
      - opengl
      - x11
      - wayland
      - audio-playback
      - gsettings

parts:

  cantara:
    plugin: nil
    source: .
    source-type: local
    build-packages:
      - build-essential
      - git
      - lcl
      - lcl-utils
      - lazarus          # Pulls in Lazarus IDE and LCL
      - fpc              # Pulls in Free Pascal Compiler
      - wget
    stage-packages:
      # - libqt5pas1       # Runtime library bundled into the final
      - libxinerama1
      - libqt6dbus6t64
      - libqt6core6t64
      - libqt6gui6t64
      - libqt6widgets6t64
      - libqt6printsupport6t64
      - libb2-1
      - libdouble-conversion3
      - libmd4c0
    stage:
      - cantara
      - languages
      - cantara.desktop
      - Cantara.ico
      - app.cantara.Cantara.png
      - usr/lib/libQt6Pas.so.6*
    override-pull: |
      craftctl default
      git submodule update --init --recursive

    override-build: |
      set -eux

      # Detect architecture and set variables accordingly
      ARCH=$(dpkg --print-architecture)
      case "$ARCH" in
        amd64)
          DEB_ARCH="amd64"
          LIB_DIR="x86_64-linux-gnu"
          ;;
        arm64)
          DEB_ARCH="arm64"
          LIB_DIR="aarch64-linux-gnu"
          ;;
        *)
          echo "Unsupported architecture: $ARCH"
          exit 1
          ;;
      esac

      # Download and install architecture-specific libqt6pas
      wget "https://github.com/davidbannon/libqt6pas/releases/download/v6.2.10/libqt6pas6-dev_6.2.10-1_${DEB_ARCH}.deb"
      wget "https://github.com/davidbannon/libqt6pas/releases/download/v6.2.10/libqt6pas6_6.2.10-1_${DEB_ARCH}.deb"
      apt install -y "./libqt6pas6_6.2.10-1_${DEB_ARCH}.deb" "./libqt6pas6-dev_6.2.10-1_${DEB_ARCH}.deb"

      cd src

      # Build required library packages with Qt6 widgetset
      lazbuild --ws=qt6 bgrabitmap/bgrabitmap/bgrabitmappack.lpk
      lazbuild --ws=qt6 metadarkstyle/metadarkstyle.lpk

      # Build Cantara with the ReleaseConfined mode (stripped, optimised, Qt6)
      lazbuild -B --bm="ReleaseConfined" --ws=qt6 Cantara.lpi

      # ── Install binary ───────────────────────────────────────────────────
      mkdir -p "$SNAPCRAFT_PART_INSTALL/"
      install -m 755 cantara "$SNAPCRAFT_PART_INSTALL/cantara"

      # ── Install data dirs (both live inside src/, not the project root) ──
      cp -r languages   "$SNAPCRAFT_PART_INSTALL/"
      cp -r backgrounds "$SNAPCRAFT_PART_INSTALL/"

      # ── Install icon (src/Cantara.ico) ───────────────────────────────────
      install -Dm644 Cantara.ico \
        "$SNAPCRAFT_PART_INSTALL/Cantara.ico"

      # ── Install PNG icon into standard hicolor theme path ────────────────
      install -Dm644 ../app.cantara.Cantara.png \
        "$SNAPCRAFT_PART_INSTALL/app.cantara.Cantara.png"

      # ── Install desktop file ─────────────────────────────────────────────
      install -Dm644 ../cantara.desktop \
        "$SNAPCRAFT_PART_INSTALL/cantara.desktop"

      # ── Copy libQt6Pas using architecture-specific path ──────────────────
      cp -r "/usr/lib/${LIB_DIR}/libQt6Pas.so.6"* "$SNAPCRAFT_PART_INSTALL/usr/lib/"

  cleanup:
    after: [cantara]
    plugin: nil
    override-prime: |
      set -eux
      rm -rf "$SNAPCRAFT_PRIME/usr/share/doc"
      rm -rf "$SNAPCRAFT_PRIME/usr/share/man"
      find "$SNAPCRAFT_PRIME/usr/share" -type d -empty -delete 2>/dev/null || true
