name: cantara
version: '2.6.1'
summary: A Song Presentation Software.
description: |
  A simple, leightweight but powerful program for song presentation in churches, small groups or at karaoke parties.
confinement: strict
icon: app.cantara.Cantara.png
base: core22
grade: stable

architectures:
  - build-on: amd64
    build-for: amd64
  #- build-on: arm64
  #  build-for: arm64

plugs: # plugs for theming, font settings, cursor and to use gtk3 file chooser
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes:sounds-themes

parts:
  lazarus:
    plugin: nil
    source: .
    source-type: local
    build-packages:
    - wget
    - libgtk2.0-dev
    override-build: |
      if [ "$SNAP_ARCH" = "amd64" ]
      then
        wget -nc "https://sourceforge.net/projects/lazarus/files/Lazarus%20Linux%20amd64%20DEB/Lazarus%203.2/lazarus-project_3.2.0-0_amd64.deb"
        wget -nc "https://sourceforge.net/projects/lazarus/files/Lazarus%20Linux%20amd64%20DEB/Lazarus%203.2/fpc-laz_3.2.2-210709_amd64.deb"
        wget -nc "https://sourceforge.net/projects/lazarus/files/Lazarus%20Linux%20amd64%20DEB/Lazarus%203.2/fpc-src_3.2.2-210709_amd64.deb"
        apt -y install "./lazarus-project_3.2.0-0_amd64.deb" "./fpc-laz_3.2.2-210709_amd64.deb" "./fpc-src_3.2.2-210709_amd64.deb"
      fi
    prime: [-*]
  cantara:
    after: [lazarus]
    plugin: nil
    source: .
    source-type: local
    build-packages:
    - build-essential
    stage-packages:
    - qt5-gtk-platformtheme
    - qtwayland5

    override-build: |
      wget -nc "https://github.com/davidbannon/libqt5pas/releases/download/v1.2.15/libqt5pas-dev_2.15-1_amd64.deb"
      wget -nc "https://github.com/davidbannon/libqt5pas/releases/download/v1.2.15/libqt5pas1_2.15-1_amd64.deb"
      apt -y install "./libqt5pas1_2.15-1_amd64.deb" "./libqt5pas-dev_2.15-1_amd64.deb"
      cd src
      lazbuild --ws="qt5" bgrabitmap/bgrabitmap/bgrabitmappack.lpk
      lazbuild -B --bm="ReleaseConfined" --ws="qt5" Cantara.lpi
      cp -r languages $SNAPCRAFT_PART_INSTALL/
      install Cantara.ico $SNAPCRAFT_PART_INSTALL/
      install cantara $SNAPCRAFT_PART_INSTALL/
      cp -r backgrounds $SNAPCRAFT_PART_INSTALL/
      cd ..
      install cantara.desktop $SNAPCRAFT_PART_INSTALL/
      install app.cantara.Cantara.png $SNAPCRAFT_PART_INSTALL/
      mkdir -p /usr/lib/x86_64-linux-gnu
      cp /usr/lib/x86_64-linux-gnu/libQt5Pas* $SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/
    stage:
    - lib
    - usr
    - etc
    - cantara
    - languages
    - cantara.desktop
    - Cantara.ico
    - app.cantara.Cantara.png
  cleanup:
    after: [cantara]
    plugin: nil
    build-snaps: [kde-frameworks-5-102-qt-5-15-8-core22]
    override-prime: |
      set -eux
      for snap in "kde-frameworks-5-102-qt-5-15-8-core22"; do  # List all content-snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" "$SNAPCRAFT_PRIME/usr/{}" \;
      done
      for cruft in bug lintian man icons; do
        rm -rf $SNAPCRAFT_PRIME/usr/share/$cruft
      done
      find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
      find $SNAPCRAFT_PRIME/usr/lib -type f,l -name 'libQt*.so*' ! -name 'libQt5Pas*.so*' -delete

apps:
  cantara:
    extensions:
      - kde-neon
    command: cantara
    desktop: cantara.desktop
    environment: 
      DISABLE_WAYLAND: 1
    plugs:
    - home
    - desktop
    - desktop-legacy
    - opengl
    - x11
    - unity7
    - wayland
    - gsettings
